### ISSUE TITLE
Sphinx docs download issues (3200)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1606]
#  **Issue &numero;3200 opened by *[BradTFT](https://github.com/BradTFT)* at 2022-05-29 04:18:38**

Hi,

I am going to be travelling soon and wanted to get a local copy of the documentation. I noticed the README in the docs folder and tried it. (im not sure if this is the right place to be putting this issue please correct me if im wrong). I installed Sphinx and forked the repo. cloned it into a folder and `cd pygame-docs-fork`. ran `python3 setup.py docs` and got this error

```
python3 setup.py docs
Traceback (most recent call last):
  File "/home/BradTFT/fork/pygame-docs-fork/setup.py", line 72, in <module>
    from setuptools import setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 35, in <module>
    from setuptools.depends import Require
  File "/usr/lib/python3/dist-packages/setuptools/depends.py", line 7, in <module>
    from .py33compat import Bytecode
  File "/usr/lib/python3/dist-packages/setuptools/py33compat.py", line 55, in <module>
    unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

i tried running `python3 setup.py docs --f` and got the same error. currently on Sphinx version ```Sphinx                        1.8.6
sphinxcontrib-websupport      1.1.2``` and python3 version 3.9.2. Not sure what else i can try for troubleshooting besides making this issue. forums were no help.<hr>

#  Comments

# # #  **[Starbuck5](https://github.com/Starbuck5)* commented at 2022-05-29 04:21:25*

We don't build on Sphinx 1.0 anymore. You need Sphinx 2 at least, but Sphinx 4 is where we generate ours.
(All that is off the top of my head so it may be wrong)

On pygame 2.1.2 you can just `python -m pygame.docs` and it will launch the locally included copy of the documentation. We bundle documentation in our distribution through pip.
<hr>

# # #  **[BradTFT](https://github.com/BradTFT)* commented at 2022-05-29 04:23:54*

so what should i do abt my sphinx version? just leave it and attempt the command mentioned?
<hr>

# # #  **[ankith26](https://github.com/ankith26)* commented at 2022-05-29 04:24:14*

Yeah, that should work
<hr>

# # #  **[BradTFT](https://github.com/BradTFT)* commented at 2022-05-29 04:25:59*

awesome. i appreciate the help. fastest thats ever gone
