### ISSUE TITLE
No command works with pygame 3.7 (696)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#532]
#  **Issue &numero;696 opened by *[LtOJ](https://github.com/LtOJ)* at 2018-12-27 06:28:50**

Pygame is installed and up to date. It is also the correct version. No other functions seem to to work either :/

# CODE
import pygame
pygame.display.set_mode([800, 600])

# ERROR
"""
Traceback (most recent call last):
  File "C:\PythonPrograms\37\pygame.py", line 1, in <module>
    import pygame
  File "C:\PythonPrograms\37\pygame.py", line 2, in <module>
    screen = pygame.display.set_mode([800, 600])
AttributeError: 'module' object has no attribute 'display'
"""<hr>

#  Comments

# # #  **[illume](https://github.com/illume)* commented at 2018-12-27 09:39:29*

Do you have a file called pygame.py?

If that's the case, python tries to load that instead of pygame. And then this is the error you get.
<hr>

# # #  **[LtOJ](https://github.com/LtOJ)* commented at 2018-12-27 19:54:04*

Thank you so much. I'm new to pygame and programming in general. This saved a lot of stress.
